config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations' }

  resources :questions do
    resources :subscribes, only: %i[create destroy], shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true, defaults: { commentable: 'answer' }
    end
    resources :comments, shallow: true, defaults: { commentable: 'question' }
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create], shallow: true
      end
    end
  end

  resources :links, only: :destroy
  resources :rewards, only: :index

  root to:'questions#index'

  get 'answer_best', to: 'answers#best'
  get 'my_rewards', to: 'rewards#index'

  get '/search', to: 'search#search'

  post 'like', to: 'likes#like', as: 'rate'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Likeable
  include Commentable
  
  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscribes, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  validates :title, :body, presence: true

  after_create :calculate_reputation

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :author_id, files: [], links_attributes: [:name, :url, :_destroy], reward_attributes: [:title, :file])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: %i[show edit update destroy]  
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_subscribe, only: %i[show update]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
    gon.current_user_id = current_user&.id
  end

  def show
    @answer = Answer.new
    @answer.links.build
    gon.current_user_id = current_user&.id
  end

  def new
    @question = current_user.questions.new
    @question.links.build
    @question.reward = Reward.new
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to question_path(@question), notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
    @questions = Question.all
  end

  def destroy
    @question.destroy
  end

  private

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      { question: @question }
    )
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :author_id, files: [], links_attributes: [:name, :url, :_destroy], reward_attributes: [:title, :file])
  end

  def set_subscribe
    @subscribe ||= current_user&.subscribes&.find_by(question: @question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
div(id="question_#{question.id}")
  p = link_to question.title, question
  p = question.body
  - if question.files.attached?
    - question.files.each do |f|
      p = link_to f.filename.to_s, url_for(f)
      - if can?(:destroy, f)
        p = button_to 'Delete file', purge_file_path(f), method: :delete
  td.action
    - if can?(:destroy, question)
      p = link_to 'Delete', question_path(question), method: :delete, remote: true
    - if can?(:edit, question)
      p = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }

      = form_with model: question, class: 'hidden', remote: true, html: { id: "edit-question-#{question.id}"} do |f|
        p
          = f.label :title, 'Your title'
          = f.text_area :title
        p
          = f.label :body, 'Your body'
          = f.text_area :body
        p
          - if question.files.attached?
            - question.files.each do |f|
              p = link_to f.filename.to_s, url_for(f)
          = f.label :files
          = f.file_field :files, multiple: true
        p
          = f.label :author_id, hidden: true
          - if user_signed_in?
            = f.text_field :author_id, value: current_user.id, hidden: true
          - else
            = f.text_field :author_id, value: 'empty', hidden: true
        p
          = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
        p
          = f.submit 'Save'
    - if can?(:like, question)
        p class = "rating-question" Rating: #{question.show_rating}

        p = link_to 'Like', rate_path(id: question.id, liked_type: 'question', liked_params: { rating: +1, user_id: current_user.id }), method: :post, remote: true, data: { type: :json }
        p = link_to 'Dislike', rate_path(id: question.id, liked_type: 'question', liked_params: { rating: -1, user_id: current_user.id }), method: :post, remote: true, data: { type: :json }

app/views/questions/destroy.js.erb
$("#question_<%= @question.id %>").remove()

app/views/questions/index.html.slim
= render 'shared/nav'

.search
  = render 'search/search'

  -if can?(:create, Question)
    p = link_to 'Ask question', new_question_path

  - if @questions.any?
    - cache collection_cache_key_for :question do
      .questions
       = render @questions

      .question-errors
        = render 'shared/errors', resource: @question
  - else
    p = 'No questions created yet.'

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Reward
  p
    = f.fields_for :reward do |r|
      p
        = r.label :title
        = r.text_field :title
      p
        = r.label :file
        = r.file_field :file

  p Links:
  p
    = f.fields_for :links do |l|
      p
        = l.label :name, 'Link name'
        = l.text_field :name
      p
        = l.label :url
        = l.text_field :url

  p = f.submit 'Ask'

app/views/questions/show.html.slim
- cache @question do
  h3 = "Question title - #{@question.title}"
  p = "Question body -  #{@question.body}"

  - if @question.files.attached?
    - @question.files.each do |f|
      p = link_to f.filename.to_s, url_for(f)

  .links
    - if @question.links.present?
      p Links:
      ul
        - @question.links.each do |link|
          div(id="link_#{link.id}")
            - if link.gist_url?
              li = link_to link.url
            - else
              li = link_to link.name, link.url
            - if can?(:destroy, link)
              p = link_to 'Delete link', link_path(link), method: :delete, remote: true

  .reward
    - if @question.reward.present?
      = image_tag(@question.reward.file, size: '100x100')

  .comments
    div class = "comments-#{@question.id}"
      p Question comments:
      = render partial: 'comments/comments', locals: { resource: @question}

  .subscribes
    - if can? :create, Subscribe
      = render 'subscribes/subscribe', question: @question

  .answers
    = render @question.answers

  .answer-errors
    = render 'shared/errors', resource: @answer
  - if user_signed_in?
    | Create new answer
    - cache @answer do
      = form_with model: [@question, @answer], class: 'new-answer', remote: true, data: { type: :json } do |f|
        p
          = f.label :body, 'Add answer'
          = f.text_area :body
        p
          = f.label :author_id, hidden: true
          = f.text_field :author_id, value: current_user.id, hidden: true
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        p Links
        p
        .links
          = f.fields_for :links do |link|
            = render 'link_fields', f: link
          .links-url
            = link_to_add_association 'add link', f, :links, class: "btn btn-info"
        p = f.submit 'Answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.questions').html('<%= j render @questions %>');
<% end %>