config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations' }

  resources :questions do
    resources :subscribes, only: %i[create destroy], shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true, defaults: { commentable: 'answer' }
    end
    resources :comments, shallow: true, defaults: { commentable: 'question' }
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create], shallow: true
      end
    end
  end

  resources :links, only: :destroy
  resources :rewards, only: :index

  root to:'questions#index'

  get 'answer_best', to: 'answers#best'
  get 'my_rewards', to: 'rewards#index'

  get '/search', to: 'search#search'

  post 'like', to: 'likes#like', as: 'rate'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
    can :search, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :create, [Question, Answer, Comment, Link, Subscribe]
    can :update, [Question, Answer], author_id: user.id
    can :destroy, [Question, Answer, Link], author_id: user.id
    can :destroy, Subscribe, user: user
    can :destroy, ActiveStorage::Attachment do |file|
      user.author_of?(file.record)
    end
    can [:like, :dislike], [Question, Answer] do |resource|
      user.not_author_of?(resource)
    end
    can :destroy, Link, linkable: { author_id: user.id }
    can :best, Answer, question: { author_id: user.id }
    can :me, User
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Likeable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'

  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :send_subscribe

  def best?(resource)
    resource.best_answer_id == self.id
  end

  def send_subscribe
    SubscribeJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, :commentable_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: URI::regexp

  def gist_url?
    self.url.include?('gist.github.com')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Likeable
  include Commentable
  
  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscribes, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  validates :title, :body, presence: true

  after_create :calculate_reputation

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :file

  validates :title, presence: true
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  has_many :answers, foreign_key: :author_id, dependent: :destroy
  has_many :questions, foreign_key: :author_id, dependent: :destroy
  has_many :rewards
  has_many :likes, dependent: :destroy, as: :likeable
  has_many :comments, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscribes, dependent: :destroy

  def author_of?(resource)
    resource.author_id == self.id
  end

  def not_author_of?(resource)
    !author_of?(resource)
  end

  def self.find_for_oauth(auth)
    FindForOauthService.new(auth).call
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["omniauth"]
        new_password = Devise.friendly_token[0, 20]
        user.password = new_password
        user.password_confirmation = new_password
      end
    end
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :authenticate_user!

  def purge
    file = ActiveStorage::Attachment.find(params[:id])
    if file.record.author == current_user
      file.purge
      redirect_back fallback_location: root_path, alert: "#{file.filename.to_s} deleted succesfully!"
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @query = params[:query]
    search_models = []
    search_models << 'question_core' if ActiveModel::Type::Boolean.new.cast(params[:search_model_question])
    search_models << 'answer_core' if ActiveModel::Type::Boolean.new.cast(params[:search_model_answer])
    search_models << 'comment_core' if ActiveModel::Type::Boolean.new.cast(params[:search_model_comment])
    search_models << 'user_core' if ActiveModel::Type::Boolean.new.cast(params[:search_model_user])

    if @query.present?
      @results = ThinkingSphinx.search(@query, indices: search_models, match_mode: :any)
      render 'search/index', results: @results, query: @query
    else
      redirect_back fallback_location: root_path, notice: "Search parameters doesn't submitted"    
    end  
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/search/_result.html.slim
- if @results.present?
  - @results.each do |result|
    .card.mb-3
    .card-body
    - if result.class == Question
      p.card-text.text-muted Title: #{result.title}
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Posted by: #{result.author.email}
      p.card-text.text-muted Question created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == Answer
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Answer to question: #{result.question.title}
      p.card-text.text-muted Posted by: #{result.author.email}
      p.card-text.text-muted Answer created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == Comment
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Comment to #{result.commentable_type}: #{result.commentable.body}
      p.card-text.text-muted Posted by: #{result.user.email}
      p.card-text.text-muted Comment created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == User
      p.card-text.text-muted Email: #{result.email} 
      p.card-text.text-muted Account created at: #{result.created_at.strftime('%B %d, %Y')}
- else
  p No results found for "#{@query}"

app/views/search/_search.html.slim
= form_tag(search_path, method: :get, class: "d-flex") do
  = text_field_tag(:query, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" })
  = label_tag :search_model_question, class: 'form-check-label' do
    = check_box_tag :search_model_question, 1, params[:search_model_question], class: 'form-check-input', name: 'search_model_question'
    | Questions
  = label_tag :search_model_answer, class: 'form-check-label' do
    = check_box_tag :search_model_answer, 1, params[:search_model_answer], class: 'form-check-input', name: 'search_model_answer'
    | Answers
  = label_tag :search_model_comment, class: 'form-check-label' do
    = check_box_tag :search_model_comment, 1, params[:search_model_comment], class: 'form-check-input', name: 'search_model_comment'
    | Comments
  = label_tag :search_model_comment, class: 'form-check-label' do
    = check_box_tag :search_model_user, 1, params[:search_model_user], class: 'form-check-input', name: 'search_model_user'
    | Users    
  = submit_tag("Search", class: "btn btn-primary")

app/views/search/index.html.slim
.search
  = render 'search/search'  

h4 Results for "#{@query}" search:

= render 'search/result'

= button_to 'To questions', questions_path, :method => :get

app/views/search/result.html.slim
- if @results.present?
  - @results.each do |result|
    .card.mb-3
    .card-body
    - if result.class == Question
      p.card-text.text-muted Title: #{result.title}
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Posted by: #{result.author.email}
      p.card-text.text-muted Question created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == Answer
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Answer to question: #{result.question.title}
      p.card-text.text-muted Posted by: #{result.author.email}
      p.card-text.text-muted Answer created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == Comment
      p.card-text.text-muted Body: #{result.body}
      p.card-text.text-muted Comment to #{result.commentable_type}: #{result.commentable.body}
      p.card-text.text-muted Posted by: #{result.user.email}
      p.card-text.text-muted Comment created at: #{result.created_at.strftime('%B %d, %Y')}
    - elsif result.class == User
      p.card-text.text-muted Email: #{result.email} 
      p.card-text.text-muted Account created at: #{result.created_at.strftime('%B %d, %Y')}
- else
  p No results found for "#{@query}"