config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations' }

  resources :questions do
    resources :subscribes, only: %i[create destroy], shallow: true
    resources :answers, shallow: true do
      resources :comments, shallow: true, defaults: { commentable: 'answer' }
    end
    resources :comments, shallow: true, defaults: { commentable: 'question' }
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create], shallow: true
      end
    end
  end

  resources :links, only: :destroy
  resources :rewards, only: :index

  root to:'questions#index'

  get 'answer_best', to: 'answers#best'
  get 'my_rewards', to: 'rewards#index'

  get '/search', to: 'search#search'

  post 'like', to: 'likes#like', as: 'rate'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Likeable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'

  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :send_subscribe

  def best?(resource)
    resource.best_answer_id == self.id
  end

  def send_subscribe
    SubscribeJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[edit destroy update best]

  after_action :publish_answer, only: [:create]

  authorize_resource

  def show; end

  def index
    @answers = Answer.all
  end

  def new; end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { render @answer }
        format.json { render json: @answer }
      else
        format.json do
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
  end

  def best
    @question = @answer.question
    @question.update(best_answer_id: @answer.id)
    current_user.rewards.push(@question.reward) if @question.reward.present?
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}",
      { answer: @answer }
    )
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :author_id, files: [], links_attributes: [:name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:create]
  before_action :find_answer, only: [:show]

  authorize_resource

  def index
    @answers = Answer.all
    render json: @answers, each_serializer: AnswerSerializer
  end

  def show
    render json: @answer, serializer: AnswerSerializer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params.merge(question_id: params[:question_id]))
    if @answer.save
      render json: @answer, serializer: AnswerSerializer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :author_id, files: [], links_attributes: [:name, :url, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div(id="answer_#{answer.id}")
  p = "Answer - #{answer.body}"

  .links
    - if answer.links.present?
      p Links:
      ul
        - answer.links.each do |link|
          div(id="link_#{link.id}")
            - if link.gist_url?
              li = link_to link.url
            - else
              li = link_to link.name, link.url
            - if can?(:destroy, link)
              p = link_to 'Delete link', link_path(link), method: :delete, remote: true

  .comments
    div class = "comments-#{answer.id}"
      p Answer comments:
      = render partial: 'comments/comments', locals: { resource: answer}

  - if answer.files.attached?
    -answer.files.each do |f|
      p = link_to f.filename.to_s, url_for(f)
      - if can?(:destroy, answer)
        p = button_to 'Delete file', purge_file_path(f), method: :delete
  - if answer.best?(answer.question)
    p = 'Best answer!'
  - elsif can?(:best, answer)
    = link_to 'Best', answer_best_path(answer, id: answer.id), method: :get, remote: true

  - if can?(:edit, answer)
    p = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

    = form_with model: answer, class: 'hidden', remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      - if answer.files.attached?
        - answer.files.each do |f|
          p = link_to f.filename.to_s, url_for(f)
      = f.label :files
      = f.file_field :files, multiple: true
      = f.label :author_id, hidden: true
      - if user_signed_in?
        = f.text_field :author_id, value: current_user.id, hidden: true
      - else
        = f.text_field :author_id, value: 'empty', hidden: true
      = f.fields_for :links do |l|
      = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
      = f.submit 'Save'

  - if can?(:destroy, answer)
    p = link_to 'Delete', answer_path(answer), method: :delete, remote: true
  - else
    p class = "rating-answer" Rating: #{answer.show_rating}

  - if user_signed_in?
    p = link_to 'Like', rate_path(id: answer.id, liked_type: 'answer', liked_params: { rating: +1, user_id: current_user.id }), method: :post, remote: true, data: { type: :json }
    p = link_to 'Dislike', rate_path(id: answer.id, liked_type: 'answer', liked_params: { rating: -1, user_id: current_user.id }), method: :post, remote: true, data: { type: :json }

app/views/answers/best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
$('.answers').html('<%= j render @answers %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$("#answer_<%= @answer.id %>").remove()

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>